default:
  image: archlinux:base-devel
  before_script:
  - pacman -Syu --noconfirm rustup
  - rustup toolchain install nightly

stages:
- sanity
- build
- test
- release

clippy:
  stage: sanity
  script:
  - rustup component add clippy
  - cargo clippy -- --deny warnings

rustfmt:
  stage: sanity
  script:
  - rustup component add rustfmt
  - cargo fmt --check

build:
  stage: build
  script:
  - cargo build

unit-test:
  stage: test
  script:
  - cargo test

release:
  stage: release
  only:
  - tags
  image:
  script:
  - buildctl build --frontend dockerfile.v0 --local dockerfile=. --local context=. --output type=image,name=${CI_REGISTRY}/concourse-gitlab-merge-request-resource:${CI_COMMIT_TAG},push=true
